### PR TITLE
add #build capability to SmartFactoryWrapper

### PR DESCRIPTION
**Pull request by acyuta108**

### CODE REVIEW

**Comment by grantspeelman** [comment]
Thank you for the suggestion @acyuta108.

I am not sure what the use case for "build" is? 
How will the rest of the test access something that is not saved to the database?

**Comment by acyuta108** [comment]
Unfortunately we have database (mariadb) constraints that require records to be build with associated records:
```
payment = build(:customer_payment)
address = build(:customer_address)
customer = create(:customer, payment: payment, address: address)
```
As you can see it is imperative that I create records using the factory #build otherwise create(:payment|:address) would raise a mysql error (child constraint). 
It is also atomic so it runs a single db transaction.
Thanks.

**Comment by grantspeelman** [comment]
```javascript
    cy.appFactories([
      ['build', 'customer_payment'],
      ['build', 'customer_address' ],
      ['create', 'customer', { payment: payment, address: address } ]
    ])
```

hmmm, unfortunately adding build won't be enough as you can't connect the various things together. ie you can't assign variables. We would also need a way to link them together.

**Comment by acyuta108** [comment]
Indeed. It would be pretty amazing if that was possible. I haven't drilled into the the gem's source code enough to see how that would work. Off the top of my head, given that all cy._method()_ calls (should) return a promise, the only thing I can think of is:
```
cy.appFactories([
  ['build', 'customer_payment'],
  ['build', 'customer_address' ]
]).then( ({ payment, address }) => {
  cy.appFactories([
    ['create', 'customer', { payment: payment, address: address } ]
  ])
})
```
I am using the #create and #build methods in an app_command/scenario which I call with something like cy.appScenario('createUserWithAddressAndPayment') in my before hook. Basically plain ruby as described in my previous comment, which works as expected in my fork.

**Comment by grantspeelman** [comment]
Hmmm not sure viable it is will be to build something like that .... though I think I understand what you are trying to accomplish.
Just first want to through some alternatives at you and let me know what if this will solve what you are trying to do. It looks to me like you are using FactoryBot/FactoryGirl.

**Comment by grantspeelman** [comment]
*pushing the logic into FactoryGirl by using traits*

```ruby
factory :customer do
  # ...
  trait :with_payment do
    payment { build(:customer_payment) }
  end

  trait :with_address do
    payment { build(:customer_address) }
  end
end
```

Now you can use the traits in your cypress specs like this:

```javascript
cy.appFactories([
      ['create', 'customer', 'with_payment', 'with_address']
    ])
```

What do you think?

**Comment by acyuta108** [comment]
Indeed! 
My style of writing specs is more declarative so I try to put most of my subject/factory building in the spec/test file itself than tucked away in the factory definition. For this case, I agree with you, this is a better solution than "pollute" this gem with more unnecessary methods (e.g: my pull request to introduce the #build method).

Now, the problem I had from the get-go was that _traits_ don't seem to work for me.. which I now recall is the reason why I started fumbling with the appScenario methodology.

I'll troubleshoot that and close this ticket. I'll file a new one if I cannot get my factories with traits to work as expected.
Thanks!

**Pull request closed without merging**
